##**Задание 1**. <br>Создание и изменение массивов

In [6]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr=arr*2
arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
arr[arr>10]=0
arr

array([[ 2,  4,  6],
       [ 8, 10,  0],
       [ 0,  0,  0]])

##**Задание 2**. <br>Работа с булевыми масками

In [7]:
arr=np.random.randint(1,101,size=20)
print(arr)

[66 13 99 88 90 45 34 92 16 68 36 83 66 86 88 18 43 98 42 41]


In [8]:
print(arr[arr%5==0])

[90 45]


In [9]:
arr[arr%5==0]=-1
print(arr)

[66 13 99 88 -1 -1 34 92 16 68 36 83 66 86 88 18 43 98 42 41]


##**Задание 3**. <br>Объединение и разбиение массивов

In [10]:
a=np.random.randint(1,50,size=(1,5))
b=np.random.randint(1,50,size=(1,5))
print(a,'\n')
print(b)

[[17  8 11 37 36]] 

[[40 42 42 39 24]]


In [11]:
c=np.concatenate((a,b),axis=0)
print(c)

[[17  8 11 37 36]
 [40 42 42 39 24]]


In [12]:
list(zip((c)))

[(array([17,  8, 11, 37, 36]),), (array([40, 42, 42, 39, 24]),)]

##**Задание 4**. <br>Генерация и работа с линейными последовательностями

In [13]:
arr = np.linspace(-10, 10, 50)
print(arr)

[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]


In [14]:
np.sum(arr)

7.105427357601002e-15

In [15]:
print(np.sum(arr[arr>0]))
print(np.sum(arr[arr<0]))

127.55102040816328
-127.55102040816327


##**Задание 5**. <br>Работа с диагональными и единичными матрицами

In [16]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
b=np.matrix('5 0 0 0;0 10 0 0; 0 0 15 0; 0 0 0 20')
b=np.array(b)
b

array([[ 5,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 20]])

In [18]:
a_s=np.sum(a)
b_s=np.sum(b)
print(a_s>b_s,a_s<b_s,a_s==b_s)

False True False


##**Задание 6**. <br>Создание и базовые операции с матрицами

In [19]:
a=np.random.randint(1,20,size=(3,3))
b=np.random.randint(1,20,size=(3,3))

In [20]:
print((a+b),'\n\n',(a-b),'\n\n',(a*b))

[[16 16 16]
 [21 11 19]
 [ 3 31 10]] 

 [[12 14 -2]
 [-1  7  5]
 [-1 -7  2]] 

 [[ 28  15  63]
 [110  18  84]
 [  2 228  24]]


##**Задание 7**. <br>Умножение матриц

In [21]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(1,10,size=(3,2))
print(np.dot(a,b))

[[160 103]
 [120  89]]


##**Задание 8**. <br>Определитель и обратная матрица

In [22]:
a=np.random.randint(1,100,size=(3,3))

In [23]:
print(np.linalg.det(a))

11888.000000000004


In [24]:
if np.linalg.det(a):
    print(np.linalg.inv(a))
else:
    print("Матрица не вырождена")

[[ 0.00336474  0.01211306 -0.0031965 ]
 [-0.6833782  -0.16016151  0.42420929]
 [ 0.11709287  0.02153432 -0.06123822]]


##**Задание 9**. <br>Транспонирование и след матрицы

In [25]:
a=np.random.randint(1,50,size=(4,4))

In [27]:
print(a)

[[ 1 17 31 36]
 [35  5 28 14]
 [30 45 43 22]
 [13 42 18 46]]


In [28]:
print(a.T)

[[ 1 35 30 13]
 [17  5 45 42]
 [31 28 43 18]
 [36 14 22 46]]


In [29]:
print(np.sum(np.diag(a)))

95


##**Задание 10**. <br>Системы линейных уравнений

In [30]:
A=np.matrix('2 3 -1;4 -1 2;-3 5 4')
A=np.array(A)
A

array([[ 2,  3, -1],
       [ 4, -1,  2],
       [-3,  5,  4]])

In [31]:
B = np.array([5, 6, -2])

In [32]:
sol = np.linalg.solve(A, B)
print(sol)

[1.63963964 0.57657658 0.00900901]


##**Задание 11**. <br>Индивидуальное задание. Продажа билетов

In [2]:
import numpy as np

A = np.array([
    [1, -1, 0],
    [1, 1, 1],
    [1, 1.5, 3]
])
B = np.array([100, 500, 600])

# Решение с помощью numpy
solution = np.linalg.solve(A, B)
print("Решение методом np.linalg.solve:")
print(f"x = {solution[0]}, y = {round(solution[1])}, z = {round(solution[2])}")

# Метод Крамера
det_A = np.linalg.det(A)

A_x = A.copy()
A_x[:, 0] = B
det_Ax = np.linalg.det(A_x)
x = det_Ax / det_A

A_y = A.copy()
A_y[:, 1] = B
det_Ay = np.linalg.det(A_y)
y = det_Ay / det_A

A_z = A.copy()
A_z[:, 2] = B
det_Az = np.linalg.det(A_z)
z = det_Az / det_A

print("\nРешение методом Крамера:")
print(f"x = {x}, y = {round(y)}, z = {round(z)}")

# Матричный метод
A_inv = np.linalg.inv(A)
solution_matrix = np.dot(A_inv, B)
print("\nРешение матричным методом:")
print(f"x = {round(solution_matrix[0])}, y = {round(solution_matrix[1])}, z = {solution_matrix[2]}")

Решение методом np.linalg.solve:
x = 300.0, y = 200, z = 0

Решение методом Крамера:
x = 300.0, y = 200, z = 0

Решение матричным методом:
x = 300, y = 200, z = 0.0
