In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [6]:

a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

32

In [15]:
c=np.array([1,2,3,4,5])
mean=np.mean(c)
std_dev=np.std(c)
print(std_dev)
print(mean)
print(c*5)

1.4142135623730951
3.0
[ 5 10 15 20 25]


In [16]:
m=np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [17]:
m[1,0]

5

In [18]:
m[1,:]

matrix([[5, 6, 7, 8]])

In [19]:
m[:,2]

matrix([[3],
        [7],
        [5]])

In [23]:
m[1,2:]


matrix([[7, 8]])

In [24]:
m[0:2,1:3]

matrix([[2, 3],
        [6, 7]])

In [25]:
cols=[0,1,3]
m[:,cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])